apiVersion: apps/v1
kind: Deployment
metadata:
  name: lectures-k8s-service-deployment
  labels:
    app: lectures-k8s-service
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: lectures-k8s-service
  template:
    metadata: 
      labels:
        app: lectures-k8s-service
    spec:
      containers:
      - name: lectures-k8s-service
        image: vittoriapac/lectures-service
        ports:
        - containerPort: 9443